import { Config } from "effect"
import { InstallationChannel } from "../installation/version"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

// Channels that default to the new effect-httpapi server backend. The legacy
// hono backend remains the default for stable (`prod`/`latest`) installs.
const HTTPAPI_DEFAULT_ON_CHANNELS = new Set(["dev", "beta", "local"])

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const INTERBASE_EXPERIMENTAL = truthy("INTERBASE_EXPERIMENTAL")
const INTERBASE_DISABLE_CLAUDE_CODE = truthy("INTERBASE_DISABLE_CLAUDE_CODE")
const INTERBASE_DISABLE_CLAUDE_CODE_SKILLS =
  INTERBASE_DISABLE_CLAUDE_CODE || truthy("INTERBASE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["INTERBASE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  INTERBASE_AUTO_SHARE: truthy("INTERBASE_AUTO_SHARE"),
  INTERBASE_AUTO_HEAP_SNAPSHOT: truthy("INTERBASE_AUTO_HEAP_SNAPSHOT"),
  INTERBASE_GIT_BASH_PATH: process.env["INTERBASE_GIT_BASH_PATH"],
  INTERBASE_CONFIG: process.env["INTERBASE_CONFIG"],
  INTERBASE_CONFIG_CONTENT: process.env["INTERBASE_CONFIG_CONTENT"],
  INTERBASE_DISABLE_AUTOUPDATE: truthy("INTERBASE_DISABLE_AUTOUPDATE"),
  INTERBASE_ALWAYS_NOTIFY_UPDATE: truthy("INTERBASE_ALWAYS_NOTIFY_UPDATE"),
  INTERBASE_DISABLE_PRUNE: truthy("INTERBASE_DISABLE_PRUNE"),
  INTERBASE_DISABLE_TERMINAL_TITLE: truthy("INTERBASE_DISABLE_TERMINAL_TITLE"),
  INTERBASE_SHOW_TTFD: truthy("INTERBASE_SHOW_TTFD"),
  INTERBASE_PERMISSION: process.env["INTERBASE_PERMISSION"],
  INTERBASE_DISABLE_DEFAULT_PLUGINS: truthy("INTERBASE_DISABLE_DEFAULT_PLUGINS"),
  INTERBASE_DISABLE_LSP_DOWNLOAD: truthy("INTERBASE_DISABLE_LSP_DOWNLOAD"),
  INTERBASE_ENABLE_EXPERIMENTAL_MODELS: truthy("INTERBASE_ENABLE_EXPERIMENTAL_MODELS"),
  INTERBASE_DISABLE_AUTOCOMPACT: truthy("INTERBASE_DISABLE_AUTOCOMPACT"),
  INTERBASE_DISABLE_MODELS_FETCH: truthy("INTERBASE_DISABLE_MODELS_FETCH"),
  INTERBASE_DISABLE_MOUSE: truthy("INTERBASE_DISABLE_MOUSE"),
  INTERBASE_DISABLE_CLAUDE_CODE,
  INTERBASE_DISABLE_CLAUDE_CODE_PROMPT: INTERBASE_DISABLE_CLAUDE_CODE || truthy("INTERBASE_DISABLE_CLAUDE_CODE_PROMPT"),
  INTERBASE_DISABLE_CLAUDE_CODE_SKILLS,
  INTERBASE_DISABLE_EXTERNAL_SKILLS: truthy("INTERBASE_DISABLE_EXTERNAL_SKILLS"),
  INTERBASE_FAKE_VCS: process.env["INTERBASE_FAKE_VCS"],
  INTERBASE_SERVER_PASSWORD: process.env["INTERBASE_SERVER_PASSWORD"],
  INTERBASE_SERVER_USERNAME: process.env["INTERBASE_SERVER_USERNAME"],
  INTERBASE_ENABLE_QUESTION_TOOL: truthy("INTERBASE_ENABLE_QUESTION_TOOL"),

  // Experimental
  INTERBASE_EXPERIMENTAL,
  INTERBASE_EXPERIMENTAL_FILEWATCHER: Config.boolean("INTERBASE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  INTERBASE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("INTERBASE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  INTERBASE_EXPERIMENTAL_ICON_DISCOVERY: INTERBASE_EXPERIMENTAL || truthy("INTERBASE_EXPERIMENTAL_ICON_DISCOVERY"),
  INTERBASE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("INTERBASE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  INTERBASE_ENABLE_EXA:
    truthy("INTERBASE_ENABLE_EXA") || INTERBASE_EXPERIMENTAL || truthy("INTERBASE_EXPERIMENTAL_EXA"),
  INTERBASE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("INTERBASE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  INTERBASE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("INTERBASE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  INTERBASE_EXPERIMENTAL_OXFMT: INTERBASE_EXPERIMENTAL || truthy("INTERBASE_EXPERIMENTAL_OXFMT"),
  INTERBASE_EXPERIMENTAL_LSP_TY: truthy("INTERBASE_EXPERIMENTAL_LSP_TY"),
  INTERBASE_EXPERIMENTAL_LSP_TOOL: INTERBASE_EXPERIMENTAL || truthy("INTERBASE_EXPERIMENTAL_LSP_TOOL"),
  INTERBASE_EXPERIMENTAL_PLAN_MODE: INTERBASE_EXPERIMENTAL || truthy("INTERBASE_EXPERIMENTAL_PLAN_MODE"),
  INTERBASE_EXPERIMENTAL_MARKDOWN: !falsy("INTERBASE_EXPERIMENTAL_MARKDOWN"),
  INTERBASE_MODELS_URL: process.env["INTERBASE_MODELS_URL"],
  INTERBASE_MODELS_PATH: process.env["INTERBASE_MODELS_PATH"],
  INTERBASE_DISABLE_EMBEDDED_WEB_UI: truthy("INTERBASE_DISABLE_EMBEDDED_WEB_UI"),
  INTERBASE_DB: process.env["INTERBASE_DB"],
  INTERBASE_DISABLE_CHANNEL_DB: truthy("INTERBASE_DISABLE_CHANNEL_DB"),
  INTERBASE_SKIP_MIGRATIONS: truthy("INTERBASE_SKIP_MIGRATIONS"),
  INTERBASE_STRICT_CONFIG_DEPS: truthy("INTERBASE_STRICT_CONFIG_DEPS"),

  // Defaults to true on dev/beta/local channels so internal users exercise the
  // new effect-httpapi server backend. Stable (`prod`/`latest`) installs stay
  // on the legacy hono backend until the rollout is complete. An explicit env
  // var ("true"/"1" or "false"/"0") always wins, providing an opt-in for
  // stable users and an escape hatch for dev/beta users.
  INTERBASE_EXPERIMENTAL_HTTPAPI:
    truthy("INTERBASE_EXPERIMENTAL_HTTPAPI") ||
    (!falsy("INTERBASE_EXPERIMENTAL_HTTPAPI") && HTTPAPI_DEFAULT_ON_CHANNELS.has(InstallationChannel)),
  INTERBASE_EXPERIMENTAL_EVENT_SYSTEM: INTERBASE_EXPERIMENTAL || truthy("INTERBASE_EXPERIMENTAL_EVENT_SYSTEM"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get INTERBASE_DISABLE_PROJECT_CONFIG() {
    return truthy("INTERBASE_DISABLE_PROJECT_CONFIG")
  },
  get INTERBASE_TUI_CONFIG() {
    return process.env["INTERBASE_TUI_CONFIG"]
  },
  get INTERBASE_CONFIG_DIR() {
    return process.env["INTERBASE_CONFIG_DIR"]
  },
  get INTERBASE_PURE() {
    return truthy("INTERBASE_PURE")
  },
  get INTERBASE_PLUGIN_META_FILE() {
    return process.env["INTERBASE_PLUGIN_META_FILE"]
  },
  get INTERBASE_CLIENT() {
    return process.env["INTERBASE_CLIENT"] ?? "cli"
  },
}
